# Gradle JVM Arguments
# Increase heap size to prevent OutOfMemoryError during builds
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Use AndroidX
android.useAndroidX=true
android.enableJetifier=false

# Stability properties
android.nonTransitiveRClass=true
android.nonFinalResIds=true

# Enable Parallel Execution
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.configuration-cache=false
